name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-forbidden-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check for replaceSubrange usage
      run: ./Scripts/check_no_replaceSubrange.sh

  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test